// Mock API responses with realistic dummy data
export const mockApiResponses = {
  // Login response
  login: {
    success: true,
    message: "Login successful",
    data: {
      user: {
        id: 1,
        email: "demo@fisecglobal.net",
        full_name: "Demo User",
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo-token",
      expires_in: 3600,
    },
  },

  // Resume upload response
  uploadResumes: {
    success: true,
    message: "Resumes uploaded successfully",
    data: {
      uploaded_count: 3,
      resumes: [
        {
          id: 1,
          filename: "john_doe_resume.pdf",
          original_name: "John Doe Resume.pdf",
          file_size: 1024000,
          content_extracted: true,
          upload_date: "2024-01-01T00:00:00Z",
        },
        {
          id: 2,
          filename: "sarah_wilson_resume.pdf",
          original_name: "Sarah Wilson Resume.pdf",
          file_size: 856000,
          content_extracted: true,
          upload_date: "2024-01-01T00:00:00Z",
        },
      ],
    },
  },

  // Get all resumes
  getResumes: {
    success: true,
    data: {
      resumes: [
        {
          id: 1,
          filename: "john_doe_resume.pdf",
          original_name: "John Doe - Senior Developer.pdf",
          file_size: 1024000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 2,
          filename: "sarah_wilson_resume.pdf",
          original_name: "Sarah Wilson - Full Stack Engineer.pdf",
          file_size: 856000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 3,
          filename: "mike_chen_resume.pdf",
          original_name: "Mike Chen - Python Developer.pdf",
          file_size: 945000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 4,
          filename: "lisa_garcia_resume.pdf",
          original_name: "Lisa Garcia - DevOps Engineer.pdf",
          file_size: 1150000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 5,
          filename: "alex_johnson_resume.pdf",
          original_name: "Alex Johnson - React Developer.pdf",
          file_size: 920000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 6,
          filename: "priya_patel_resume.pdf",
          original_name: "Priya Patel - Data Scientist.pdf",
          file_size: 1080000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 7,
          filename: "david_brown_resume.pdf",
          original_name: "David Brown - Backend Engineer.pdf",
          file_size: 990000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 8,
          filename: "maria_rodriguez_resume.pdf",
          original_name: "Maria Rodriguez - UI/UX Designer.pdf",
          file_size: 1200000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 9,
          filename: "james_taylor_resume.pdf",
          original_name: "James Taylor - Cloud Architect.pdf",
          file_size: 1100000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
        {
          id: 10,
          filename: "anna_kim_resume.pdf",
          original_name: "Anna Kim - Frontend Developer.pdf",
          file_size: 890000,
          upload_date: "2024-01-01T00:00:00Z",
          last_matched: "2024-01-02T10:30:00Z",
        },
      ],
      pagination: {
        current_page: 1,
        total_pages: 1,
        total_items: 10,
        items_per_page: 10,
      },
    },
  },

  // Resume matching response with varied scores
  matchResumes: {
    success: true,
    message: "Resume matching completed",
    data: {
      job_analysis: {
        key_skills: ["Python", "React", "AWS", "Docker", "REST APIs"],
        experience_level: "Senior",
        job_category: "Software Development",
      },
      matched_resumes: [
        {
          id: 2,
          filename: "sarah_wilson_resume.pdf",
          original_name: "Sarah Wilson - Full Stack Engineer.pdf",
          match_score: 94,
          max_score: 100,
          matching_skills: [
            "Python",
            "React",
            "AWS",
            "Docker",
            "REST APIs",
            "PostgreSQL",
          ],
          missing_skills: [],
          experience_match: "Senior (7 years)",
          summary:
            "Excellent match with all required skills and strong experience",
          strengths: [
            "7+ years full-stack development",
            "Expert in Python and React ecosystem",
            "Strong AWS and DevOps background",
            "Led multiple high-impact projects",
          ],
          weaknesses: [],
        },
        {
          id: 1,
          filename: "john_doe_resume.pdf",
          original_name: "John Doe - Senior Developer.pdf",
          match_score: 89,
          max_score: 100,
          matching_skills: ["Python", "React", "AWS", "Docker"],
          missing_skills: ["GraphQL"],
          experience_match: "Senior (6 years)",
          summary: "Strong match with excellent Python and React experience",
          strengths: [
            "6+ years Python development",
            "React expertise with modern frameworks",
            "AWS cloud architecture experience",
            "Strong problem-solving skills",
          ],
          weaknesses: [
            "Limited GraphQL experience",
            "No mention of microservices architecture",
          ],
        },
        {
          id: 9,
          filename: "james_taylor_resume.pdf",
          original_name: "James Taylor - Cloud Architect.pdf",
          match_score: 85,
          max_score: 100,
          matching_skills: ["AWS", "Docker", "Python", "Kubernetes"],
          missing_skills: ["React"],
          experience_match: "Senior (8 years)",
          summary:
            "Strong backend and cloud expertise, limited frontend experience",
          strengths: [
            "8+ years cloud architecture",
            "Expert in AWS and containerization",
            "Strong Python and backend skills",
            "DevOps and infrastructure expertise",
          ],
          weaknesses: [
            "Limited React/frontend experience",
            "Focus more on infrastructure than application development",
          ],
        },
        {
          id: 4,
          filename: "lisa_garcia_resume.pdf",
          original_name: "Lisa Garcia - DevOps Engineer.pdf",
          match_score: 78,
          max_score: 100,
          matching_skills: ["AWS", "Docker", "Python", "Kubernetes"],
          missing_skills: ["React", "REST APIs"],
          experience_match: "Mid-Senior (5 years)",
          summary:
            "Strong DevOps background, some gaps in application development",
          strengths: [
            "5+ years DevOps experience",
            "Expert in AWS and containerization",
            "Strong automation and CI/CD skills",
            "Python scripting expertise",
          ],
          weaknesses: [
            "Limited application development experience",
            "No React or frontend skills",
            "Minimal REST API development",
          ],
        },
        {
          id: 3,
          filename: "mike_chen_resume.pdf",
          original_name: "Mike Chen - Python Developer.pdf",
          match_score: 76,
          max_score: 100,
          matching_skills: ["Python", "REST APIs", "Docker"],
          missing_skills: ["React", "AWS"],
          experience_match: "Mid-level (4 years)",
          summary: "Strong Python skills but limited full-stack experience",
          strengths: [
            "4+ years Python development",
            "Strong backend development skills",
            "Experience with REST APIs and databases",
            "Good understanding of software architecture",
          ],
          weaknesses: [
            "No React or frontend experience",
            "Limited cloud/AWS knowledge",
            "Lacks senior-level experience",
          ],
        },
        {
          id: 5,
          filename: "alex_johnson_resume.pdf",
          original_name: "Alex Johnson - React Developer.pdf",
          match_score: 72,
          max_score: 100,
          matching_skills: ["React", "REST APIs", "Docker"],
          missing_skills: ["Python", "AWS"],
          experience_match: "Mid-level (4 years)",
          summary: "Strong frontend skills but limited backend experience",
          strengths: [
            "4+ years React development",
            "Modern frontend technologies expert",
            "Strong UI/UX understanding",
            "Experience with state management",
          ],
          weaknesses: [
            "Limited Python/backend experience",
            "No cloud/AWS knowledge",
            "Lacks full-stack development experience",
          ],
        },
        {
          id: 10,
          filename: "anna_kim_resume.pdf",
          original_name: "Anna Kim - Frontend Developer.pdf",
          match_score: 68,
          max_score: 100,
          matching_skills: ["React", "REST APIs"],
          missing_skills: ["Python", "AWS", "Docker"],
          experience_match: "Junior-Mid (3 years)",
          summary:
            "Good frontend skills but limited backend and DevOps knowledge",
          strengths: [
            "3+ years frontend development",
            "Strong React and JavaScript skills",
            "Good understanding of modern web standards",
            "Experience with responsive design",
          ],
          weaknesses: [
            "No Python/backend experience",
            "Limited cloud and DevOps knowledge",
            "Junior-level experience",
          ],
        },
        {
          id: 6,
          filename: "priya_patel_resume.pdf",
          original_name: "Priya Patel - Data Scientist.pdf",
          match_score: 55,
          max_score: 100,
          matching_skills: ["Python"],
          missing_skills: ["React", "AWS", "Docker", "REST APIs"],
          experience_match: "Senior (6 years) - Different domain",
          summary: "Strong Python skills but different specialization",
          strengths: [
            "6+ years Python development",
            "Expert in data analysis and ML",
            "Strong mathematical and analytical skills",
            "Experience with Python data stack",
          ],
          weaknesses: [
            "No web development experience",
            "Different career focus (Data Science vs Web Dev)",
            "No experience with web frameworks",
          ],
        },
        {
          id: 7,
          filename: "david_brown_resume.pdf",
          original_name: "David Brown - Backend Engineer.pdf",
          match_score: 71,
          max_score: 100,
          matching_skills: ["Python", "REST APIs", "Docker"],
          missing_skills: ["React", "AWS"],
          experience_match: "Mid-Senior (5 years)",
          summary: "Solid backend skills with some technology gaps",
          strengths: [
            "5+ years backend development",
            "Strong Python and API development",
            "Database design expertise",
            "Good software architecture understanding",
          ],
          weaknesses: [
            "No frontend/React experience",
            "Limited cloud platform knowledge",
            "Primarily focused on backend only",
          ],
        },
        {
          id: 8,
          filename: "maria_rodriguez_resume.pdf",
          original_name: "Maria Rodriguez - UI/UX Designer.pdf",
          match_score: 32,
          max_score: 100,
          matching_skills: [],
          missing_skills: ["Python", "React", "AWS", "Docker", "REST APIs"],
          experience_match: "Different role (5 years design)",
          summary: "Design expertise but minimal development skills",
          strengths: [
            "5+ years UI/UX design",
            "Strong visual design skills",
            "User experience expertise",
            "Understanding of design systems",
          ],
          weaknesses: [
            "No programming experience",
            "Different career path entirely",
            "Would require significant retraining",
          ],
        },
      ],
      matching_stats: {
        total_resumes_analyzed: 10,
        resumes_with_matches: 9,
        average_score: 69,
        processing_time_ms: 2340,
      },
    },
  },
};
